# Generated by Django 4.1.4 on 2022-12-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='contib',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='email',
            field=models.EmailField(default=0.0, max_length=254),
            preserve_default=False,
        ),
    ]
